Output demo.gif

Set FontFamily "JetBrainsMono Nerd Font"
Set FontSize 18

Set Width 1280
Set Height 1200

Set Theme "Catpuccin Mocha"

# Setup
Hide
Type "go build ."
Enter
Type "./lolesport"
Enter
Wait+Screen /Rift/
Show

# Show case schedule
Sleep 2s
Enter
Sleep 2s
Down@500ms 10
Sleep 2s
Tab

# Select split
Sleep 2s
Up@500ms 2
Enter

# Select league
Sleep 2s
Down@500ms 4
Right

# Showcase ranking
Sleep 2s
Right
Down@250ms 15
Escape

# Showcase bracket
Sleep 2s
Down
Sleep 500ms
Right
Sleep 5s
